### ISSUE TITLE
Performed experiments to collect data

### ISSUE THREAD

**Issue by GinesGarcia** [wineslab/colosseum-oran-commag-dataset#1]
Hi,
first of all thanks a lot for sharing this dataset with the research community. It will for sure be useful for a lot of people.

My question is related to the type of experiments you performed to collect this dataset (vide traffic, browsing traffic, ...) and how did you collect the data (ad-hoc software componets, srsLTE/OAI metrics, ...).

Thanks in advance,
Ginés.

**Comment by leonardobonati** [comment]
Dear Gines,

Thank you for your interest in our work. Experiments and data collection are detailed in the following paper: <a href="https://arxiv.org/pdf/2012.01263.pdf" target="_blank">arXiv:2012.01263</a>. Kindly refer to Section IV for more details.

Best Regards,
Leonardo

**Comment by GinesGarcia** [comment]
Thanks a lot for your reply. 

I'll re-check this section.

Regads,
Ginés.
