### ISSUE TITLE
time window in timestamps label

### ISSUE THREAD

**Issue by fahriwm** [wineslab/colosseum-oran-commag-dataset#2]
Hello,

First of all, I would like to thank you for sharing this data. 

I have a question related to the timestamps. In the paper, you mentioned that this data belongs to near real-time control loops (10-1000ms). However, I want to know about the exact time window between timestamps. I believe it would be handy, particularly if we're going to consider multiscale time-series

thank you

**Comment by leonardobonati** [comment]
Hi,

Thank you for your interest in our work. This dataset contains entries that are recorded every 250ms (&#177; processor drift time). Logging is made locally by the base stations. In-between time windows, the base stations execute the last policy signaled by the RIC.

Best Regards,
Leonardo
